name: Build CDOX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure CMake
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: "CDOX/CMakeLists.txt"
        workflowPreset: "default"
        buildPreset: "default"

    - name: Build with CMake
      run: cmake --build build --config Release
