name: Build CDOX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt6 and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-base-dev-tools qt6-networkauth-dev qt6-tools-dev qt6-tools-dev-tools

    - name: Configure CMake
      run: cmake -S CDOX -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release
